version: '3.8'

services:
    nginx: 
        image: aturyng/cryptagram-frontend:latest
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/frontend/dev/Dockerfile
        ports:
            - 80:80
        volumes:
            - static_volume:/app/backend/static
            - ./docker/nginx/development:/etc/nginx/conf.d
        depends_on: 
            - backend
    backend:
        image: aturyng/cryptagram-backend:latest
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/dev/Dockerfile 
        entrypoint: /app/docker/backend/dev/entrypoint.sh
        volumes:
            - .:/app
            - static_volume:/app/backend/static
        expose:
            - 8000        
        depends_on:
            - db
    db:
        image: postgres:15.3
        volumes:
        - postgres_data:/var/lib/postgresql/data/
        environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres

    redis:
      image: redis:alpine

    celery:
      build: ./project
      command: celery -A core worker -l info
      volumes:
        - ./backend/:/usr/src/app/
      environment:
        - DEBUG=1
        - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      depends_on:
        - redis

    celery-beat:
      build: ./project
      command: celery -A core beat -l info
      volumes:
        - ./backend/:/usr/src/app/
      environment:
        - DEBUG=1
        - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      depends_on:
        - redis

volumes:
    static_volume:
    postgres_data:
    celery_volume: