version: '3.8'

services:
    frontend: 
        image: aturyng/cryptagram-frontend:latest
        user: ${MY_UID}:${MY_GID}
        build:
            context: .
            dockerfile: ./docker/frontend/dev/Dockerfile
            args:
              - "UID=${UID:-1000}"
              - "GID=${GID:-1000}"
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        ports:
            - 5173:5173
        volumes:
            - ./frontend:/app/scr
        depends_on: 
            - backend
    backend:
        user: ${MY_UID}:${MY_GID}
        build:
            context: ./docker/backend/dev
            args:
              - "UID=${UID:-1000}"
              - "GID=${GID:-1000}"
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        entrypoint: /app/config/entrypoint.sh
        volumes:
            - ./backend:/app/src
        ports:
            - 8000:8000
        env_file:
            - ./docker/backend/dev/.env
        depends_on:
            - db
    db:
        image: postgres:15.3
        volumes:
        - postgres_data:/var/lib/postgresql/data/
        environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres

volumes:
    postgres_data: