version: '3.8'

services:
    frontend:
        extends:
            file: docker-compose.yml
            service: frontend
        ports:
            - 80:80
        volumes:
            - ./docker/frontend/dev/nginx-conf:/etc/nginx/conf.d
        depends_on: 
            - backend

    backend:
        extends:
            file: docker-compose.yml
            service: backend
        env_file:
            - ./docker/backend/dev/.env
        depends_on:
            - db

    db:
        extends:
            file: docker-compose.yml
            service: db
        ports:
            - 5432:5432

    tasks-runner:
        extends:
            file: docker-compose.yml
            service: tasks-runner
        depends_on:
            - backend

volumes:
    static_volume:
    postgres_data: