
# The first stage
# Build React static files
FROM node:lts-slim

# 'default_user' is used if non is provided
#ARG UNAME=dockeruser
#ARG UID=1000
#ARG GID=1000
#RUN groupadd -g $GID -o $UNAME
#RUN useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME
#USER $UNAME

WORKDIR /app/scr